// Centralized Mock Data for ClinixAI

export const doctors = [
  {
    id: 'dr-001',
    name: 'Dr. Sarah Mitchell',
    specialty: 'Cardiology',
    email: 'sarah.mitchell@clinixai.com',
    phone: '+1-555-2001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    status: 'online',
    rating: 4.8,
    patients: 124,
    role: 'doctor',
  },
  {
    id: 'dr-002',
    name: 'Dr. James Chen',
    specialty: 'Neurology',
    email: 'james.chen@clinixai.com',
    phone: '+1-555-2002',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    status: 'online',
    rating: 4.9,
    patients: 89,
    role: 'doctor',
  },
  {
    id: 'dr-003',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Oncology',
    email: 'emily.rodriguez@clinixai.com',
    phone: '+1-555-2003',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    status: 'offline',
    rating: 4.7,
    patients: 156,
    role: 'doctor',
  },
  {
    id: 'dr-004',
    name: 'Dr. Michael Thompson',
    specialty: 'Pediatrics',
    email: 'michael.thompson@clinixai.com',
    phone: '+1-555-2004',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    status: 'online',
    rating: 4.9,
    patients: 203,
    role: 'doctor',
  },
  {
    id: 'dr-005',
    name: 'Dr. Lisa Wang',
    specialty: 'Dermatology',
    email: 'lisa.wang@clinixai.com',
    phone: '+1-555-2005',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    status: 'online',
    rating: 4.6,
    patients: 98,
    role: 'doctor',
  },
];

export const patients = [
  {
    id: 'pt-001',
    name: 'John Anderson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    age: 45,
    condition: 'Hypertension',
    status: 'stable',
    lastVisit: '2024-04-28',
  },
  {
    id: 'pt-002',
    name: 'Maria Garcia',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    age: 38,
    condition: 'Type 2 Diabetes',
    status: 'monitoring',
    lastVisit: '2024-04-25',
  },
  {
    id: 'pt-003',
    name: 'Robert Zhang',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    age: 52,
    condition: 'Chronic Pain',
    status: 'stable',
    lastVisit: '2024-04-26',
  },
];

export const appointments = [
  {
    id: 'apt-001',
    doctorId: 'dr-001',
    patientId: 'pt-001',
    date: '2024-05-15',
    time: '10:00 AM',
    type: 'Follow-up',
    status: 'scheduled',
    notes: 'Blood pressure monitoring',
  },
  {
    id: 'apt-002',
    doctorId: 'dr-002',
    patientId: 'pt-002',
    date: '2024-05-16',
    time: '2:30 PM',
    type: 'Consultation',
    status: 'scheduled',
    notes: 'Diabetes management review',
  },
  {
    id: 'apt-003',
    doctorId: 'dr-004',
    patientId: 'pt-003',
    date: '2024-05-17',
    time: '11:00 AM',
    type: 'Assessment',
    status: 'scheduled',
    notes: 'Pain level assessment and treatment plan',
  },
];

export const consultations = [
  {
    id: 'cons-001',
    doctorId: 'dr-001',
    patientId: 'pt-001',
    startTime: '2024-05-01T09:00:00',
    endTime: '2024-05-01T09:35:00',
    duration: 35,
    status: 'completed',
    aiSummary: 'Patient presents with stable hypertension, BP readings within target range. Medication compliance excellent.',
    transcript: 'Doctor: How have you been feeling?\nPatient: Good, no major changes.\nDoctor: Great, continue current medication.',
  },
  {
    id: 'cons-002',
    doctorId: 'dr-002',
    patientId: 'pt-002',
    startTime: '2024-05-01T14:00:00',
    endTime: null,
    duration: 0,
    status: 'in-progress',
    aiSummary: 'Consultation in progress - diabetes management discussion',
    transcript: 'Doctor: Let\'s review your glucose logs...',
  },
];

export const prescriptions = [
  {
    id: 'rx-001',
    patientId: 'pt-001',
    medication: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    duration: '90 days',
    prescribedDate: '2024-04-01',
    status: 'active',
  },
  {
    id: 'rx-002',
    patientId: 'pt-002',
    medication: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    duration: '90 days',
    prescribedDate: '2024-03-15',
    status: 'active',
  },
  {
    id: 'rx-003',
    patientId: 'pt-003',
    medication: 'Gabapentin',
    dosage: '300mg',
    frequency: 'Three times daily',
    duration: '60 days',
    prescribedDate: '2024-04-10',
    status: 'active',
  },
];

export const billingData = [
  {
    id: 'bill-001',
    patientId: 'pt-001',
    date: '2024-04-15',
    amount: 250,
    status: 'paid',
    service: 'Consultation',
  },
  {
    id: 'bill-002',
    patientId: 'pt-002',
    date: '2024-04-20',
    amount: 180,
    status: 'pending',
    service: 'Lab Work',
  },
  {
    id: 'bill-003',
    patientId: 'pt-003',
    date: '2024-04-25',
    amount: 320,
    status: 'paid',
    service: 'Imaging',
  },
];

export const analyticsData = [
  {
    month: 'Jan',
    consultations: 145,
    revenue: 28500,
    patients: 324,
    satisfaction: 92,
  },
  {
    month: 'Feb',
    consultations: 168,
    revenue: 32400,
    patients: 356,
    satisfaction: 94,
  },
  {
    month: 'Mar',
    consultations: 182,
    revenue: 35600,
    patients: 389,
    satisfaction: 95,
  },
  {
    month: 'Apr',
    consultations: 196,
    revenue: 38800,
    patients: 412,
    satisfaction: 96,
  },
  {
    month: 'May',
    consultations: 210,
    revenue: 42000,
    patients: 445,
    satisfaction: 97,
  },
];

export const adminMetrics = {
  totalUsers: 1248,
  activeUsers: 847,
  totalRevenue: 178300,
  systemHealth: 99.8,
  activeConsultations: 24,
  pendingRequests: 13,
  averageResponseTime: 1.2, // seconds
  uptime: 99.95,
};

export const clinicData = {
  name: 'ClinixAI Healthcare Network',
  totalClinics: 12,
  totalDoctors: 148,
  totalPatients: 15240,
  monthlyAppointments: 8540,
  avgConsultationDuration: 28.5,
};

export const aiOutputExamples = [
  {
    id: 'ai-001',
    patientId: 'pt-001',
    title: 'Cardiac Risk Assessment',
    patient: 'John Anderson',
    date: '2024-04-28',
    riskLevel: 'moderate',
    diagnosis: 'Stage 1 Hypertension with elevated cardiovascular risk markers',
    analysis:
      'Patient presents with consistently elevated blood pressure readings averaging 145/92 mmHg over the past 3 months. BMI of 28.4 indicates overweight status contributing to cardiovascular strain. Family history of coronary artery disease on paternal side increases risk profile. Recent lipid panel shows LDL trending upward at 142 mg/dL.',
    keyFindings: [
      'Blood pressure elevated at 145/92 mmHg',
      'BMI indicates overweight status (28.4)',
      'Family history of heart disease present',
      'LDL cholesterol trending upward at 142 mg/dL',
    ],
    medications: [
      'Lisinopril 10mg — once daily (continue)',
      'Aspirin 81mg — once daily (new)',
    ],
    recommendations: [
      'Increase aerobic exercise to 150 min/week',
      'Implement low-sodium diet (<2g/day)',
      'Consider statin therapy at next visit',
      'Follow-up in 3 months with lipid panel',
    ],
    followUp: '3 months',
    confidenceScore: 94,
  },
  {
    id: 'ai-002',
    patientId: 'pt-002',
    title: 'Diabetes Management Plan',
    patient: 'Maria Garcia',
    date: '2024-04-27',
    riskLevel: 'low',
    diagnosis: 'Type 2 Diabetes Mellitus — well controlled',
    analysis:
      'Patient demonstrates excellent glycemic control with HbA1c at 6.8%, within the target range of <7%. Continuous glucose monitoring logs show consistent readings with minimal hypoglycemic episodes. No peripheral neuropathy detected on examination. Renal function tests within normal limits (eGFR 82 mL/min).',
    keyFindings: [
      'HbA1c within target range (6.8%)',
      'Glucose monitoring logs consistent',
      'No signs of peripheral neuropathy',
      'Kidney function normal (eGFR 82)',
    ],
    medications: [
      'Metformin 500mg — twice daily (continue)',
      'Vitamin D 1000 IU — once daily (continue)',
    ],
    recommendations: [
      'Continue current medication regimen',
      'Maintain current diet and exercise plan',
      'Annual eye exam for diabetic retinopathy',
      'Quarterly HbA1c check-ups',
    ],
    followUp: '3 months',
    confidenceScore: 97,
  },
  {
    id: 'ai-003',
    patientId: 'pt-003',
    title: 'Chronic Pain Assessment',
    patient: 'Robert Zhang',
    date: '2024-04-26',
    riskLevel: 'high',
    diagnosis: 'Chronic lower back pain with possible lumbar disc herniation',
    analysis:
      'Patient reports persistent lower back pain rated 7/10 on VAS scale, radiating to left leg consistent with L4-L5 dermatomal distribution. MRI findings suggest moderate disc herniation at L4-L5 with mild nerve root compression. Current gabapentin regimen provides partial relief. Physical therapy compliance has been inconsistent.',
    keyFindings: [
      'Pain rated 7/10 on VAS scale',
      'Radiculopathy pattern L4-L5 distribution',
      'MRI: moderate disc herniation L4-L5',
      'Inconsistent physical therapy attendance',
    ],
    medications: [
      'Gabapentin 300mg — three times daily (continue)',
      'Cyclobenzaprine 5mg — as needed for spasms',
    ],
    recommendations: [
      'Increase physical therapy to 3x/week',
      'Consider epidural steroid injection',
      'Refer to pain management specialist',
      'Follow-up in 4 weeks',
    ],
    followUp: '4 weeks',
    confidenceScore: 88,
  },
];

export const clinics = [
  {
    id: 'cl-001',
    name: 'Downtown Medical Center',
    address: '123 Main St, New York, NY 10001',
    phone: '+1-555-1001',
    email: 'downtown@clinixai.com',
    doctors: 24,
    patients: 3840,
    status: 'active',
    type: 'General Practice',
  },
  {
    id: 'cl-002',
    name: 'Westside Cardiology Clinic',
    address: '456 West Ave, Los Angeles, CA 90001',
    phone: '+1-555-1002',
    email: 'westside@clinixai.com',
    doctors: 12,
    patients: 1920,
    status: 'active',
    type: 'Cardiology',
  },
  {
    id: 'cl-003',
    name: 'Northgate Pediatrics',
    address: '789 North Blvd, Chicago, IL 60601',
    phone: '+1-555-1003',
    email: 'northgate@clinixai.com',
    doctors: 8,
    patients: 2100,
    status: 'active',
    type: 'Pediatrics',
  },
  {
    id: 'cl-004',
    name: 'Eastside Neurology',
    address: '321 East Rd, Houston, TX 77001',
    phone: '+1-555-1004',
    email: 'eastside@clinixai.com',
    doctors: 6,
    patients: 980,
    status: 'inactive',
    type: 'Neurology',
  },
];

export const auditLogs = [
  {
    id: 'log-001',
    user: 'Admin User',
    action: 'User Created',
    target: 'Dr. Sarah Mitchell',
    timestamp: '2024-05-01T10:15:00',
    ip: '192.168.1.10',
    status: 'success',
  },
  {
    id: 'log-002',
    user: 'Admin User',
    action: 'Settings Updated',
    target: 'System Configuration',
    timestamp: '2024-05-01T09:30:00',
    ip: '192.168.1.10',
    status: 'success',
  },
  {
    id: 'log-003',
    user: 'Dr. James Chen',
    action: 'Login',
    target: 'Authentication',
    timestamp: '2024-05-01T08:45:00',
    ip: '192.168.1.22',
    status: 'success',
  },
  {
    id: 'log-004',
    user: 'Unknown',
    action: 'Login Failed',
    target: 'Authentication',
    timestamp: '2024-05-01T08:12:00',
    ip: '203.0.113.45',
    status: 'failed',
  },
  {
    id: 'log-005',
    user: 'Admin User',
    action: 'Clinic Deactivated',
    target: 'Eastside Neurology',
    timestamp: '2024-04-30T16:20:00',
    ip: '192.168.1.10',
    status: 'success',
  },
  {
    id: 'log-006',
    user: 'Emma Johnson',
    action: 'Patient Record Accessed',
    target: 'John Anderson (pt-001)',
    timestamp: '2024-04-30T14:05:00',
    ip: '192.168.1.15',
    status: 'success',
  },
];

export const systemAlerts = [
  {
    id: 'alert-001',
    type: 'warning',
    message: 'High consultation queue - 24 pending consultations',
    timestamp: '2024-05-01T10:15:00',
    severity: 'medium',
  },
  {
    id: 'alert-002',
    type: 'info',
    message: 'System backup completed successfully',
    timestamp: '2024-05-01T03:00:00',
    severity: 'low',
  },
  {
    id: 'alert-003',
    type: 'warning',
    message: 'Dr. Chen approaching monthly consultation limit',
    timestamp: '2024-05-01T09:30:00',
    severity: 'medium',
  },
];
